- type: http
  url: https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt

- type: http
  url: https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-http.txt

- type: http
  url: https://raw.githubusercontent.com/mertguvencli/http-proxy-list/main/proxy-list/data.txt

- type: http
  url: https://raw.githubusercontent.com/MuRongPIG/Proxy-Master/main/http.txt

- type: http
  url: https://raw.githubusercontent.com/prxchk/proxy-list/main/http.txt

- type: http
  url: https://raw.githubusercontent.com/proxylist-to/proxy-list/main/http.txt

- type: http
  url: https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt

- type: http
  url: https://raw.githubusercontent.com/monosans/proxy-list/main/proxies_anonymous/http.txt

- type: https
  url: https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-https.txt

- type: https
  url: https://raw.githubusercontent.com/roosterkid/openproxylist/main/HTTPS_RAW.txt

- type: socks4
  url: https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks4.txt

- type: socks4
  url: https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks4.txt

- type: socks4
  url: https://raw.githubusercontent.com/MuRongPIG/Proxy-Master/main/socks4.txt

- type: socks4
  url: https://raw.githubusercontent.com/prxchk/proxy-list/main/socks4.txt

- type: socks4
  url: https://raw.githubusercontent.com/proxylist-to/proxy-list/main/socks4.txt

- type: socks4
  url: https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks4.txt

- type: socks4
  url: https://raw.githubusercontent.com/monosans/proxy-list/main/proxies_anonymous/socks4.txt

- type: socks4
  url: https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS4_RAW.txt

- type: socks5
  url: https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt

- type: socks5
  url: https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks5.txt

- type: socks5
  url: https://raw.githubusercontent.com/MuRongPIG/Proxy-Master/main/socks5.txt

- type: socks5
  url: https://raw.githubusercontent.com/prxchk/proxy-list/main/socks5.txt

- type: socks5
  url: https://raw.githubusercontent.com/proxylist-to/proxy-list/main/socks5.txt

- type: socks5
  url: https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks5.txt

- type: socks5
  url: https://raw.githubusercontent.com/monosans/proxy-list/main/proxies_anonymous/socks5.txt

- type: socks5
  url: https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS5_RAW.txt
